### ISSUE TITLE
UI một số chỗ tệ vcl =))))

### ISSUE THREAD

**Issue by nowl-it** [minh1107/OEINQM#1]
![image](https://github.com/minh1107/OEINQM/assets/83193108/d9f84a47-fb44-4cfc-b975-73b381848960)
quả font chữ chưa ăn =))

![image](https://github.com/minh1107/OEINQM/assets/83193108/dce8428f-29df-48e2-8ee8-f0786ae564ef)
kéo xuống đoạn này giật tung l**, UI khi zoom lên thì quá nhanh, khi di chuột ra thì giật đùng 1 phát không có hiệu ứng

**Comment by minh1107** [comment]
thằng wibu này mày rảnh háng à
